### PR TITLE
Some additional tools to draw/remove markers

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Just a couple of new actions to can remove markers, and draw lines.

"Remove Marker" and "Remove Markers" can be a bit confusing... Unfortunately I can't find a better approach...

### CODE REVIEW

**Comment by gajop** [comment]
You can use a for loop:
https://imgur.com/a/wTX6J

I would also not use an array for drawing one line. Use two points, similar to how number operations are done here:
https://github.com/sanguinariojoe/SpringBoard-Core/blob/63778fa2182a5795050e787fbe4c2f604a75b0d6/triggers/core.lua#L814-L832

**Comment by sanguinariojoe** [comment]
> You can use a for loop:
> https://imgur.com/a/wTX6J

Awesome! The we are removing "Remove Markers"

> I would also not use an array for drawing lines. Use two points, similar to how number operations are done here:
> https://github.com/sanguinariojoe/SpringBoard-Core/blob/63778fa2182a5795050e787fbe4c2f604a75b0d6/triggers/core.lua#L814-L832

I don't know man... The main benefit of this approach is that you can insert complex draws... Otherwise you'll need to add a lot of triggers (since "for each" cannot be used to get pairs of positions)

**Comment by gajop** [comment]
I think we could have both. A simple point to point `DRAW_LINE` action and a `DRAW_CONNECTED_LINES` or something similarly named (maybe there's a better name, OpenGL calls this LINE_STRIP)

**Comment by sanguinariojoe** [comment]
Done! (and tested)

**Comment by gajop** [comment]
Looks good, thanks!

**Pull request merged**
