### PR TITLE
Significantly reduced the spring_lua_alloc_log_error issues

### PR DESCRIPTION
**Pull request by sanguinariojoe**
I suffered a lot of times the following issue when loading a project:
```
(...)
[f=0000901] [SpringBoard] Reload completed successfully
[f=0000901] [SpringBoard] Validating trggers...
[f=0000901] [SpringBoard] Trigger validation complete.
[f=0000915] [SpringBoard] Engine texture: splat_normals3
[f=0000915] [SpringBoard] Engine texture: splat_distr
[f=0000915] [SpringBoard] Engine texture: splat_normals0
[f=0000915] [SpringBoard] Engine texture: splat_normals2
[f=0000915] [SpringBoard] Engine texture: specular
[f=0000915] [SpringBoard] Engine texture: splat_normals1
[f=0000922] Error: Spring.SetHeightMapFunc: error(4) = not enough memory
[f=0000922] Fatal: [spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={805506402,805306368}bytes
[f=0000922] Fatal: [spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={805506402,805306368}bytes
[f=0000922] Error: [LuaUI::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=IsAbove trace=[Internal Lua error: Call failure] not enough memory
[f=0000937] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805506519,805306368}bytes
[f=0000937] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805506519,805306368}bytes
[f=0000952] Fatal: [Game::ClientReadNet][LOGMSG] sender="Player" string="[spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={805506402,805306368}bytes"
[f=0000952] Fatal: [Game::ClientReadNet][LOGMSG] sender="Player" string="[spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={805506402,805306368}bytes"
[f=0000952] Fatal: [Game::ClientReadNet][LOGMSG] sender="Player" string="[spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805506519,805306368}bytes"
[f=0000952] Fatal: [Game::ClientReadNet][LOGMSG] sender="Player" string="[spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={805506519,805306368}bytes"
(...)
```

This simple patch is helping me a lot. What do you think?

### CODE REVIEW

**Comment by gajop** [comment]
I think there are Lua memory issues (especially at the beginning), but this is mostly related to Chili. It's allocating too much memory for Chili objects (Chili objects are memory heavy). 

In any case, I don't think the problem is with texture_manager.lua - so the solution shouldn't be placed there either. Textures actually don't count to the 800MB Lua memory limits.

**Comment by gajop** [comment]
Also, this problem probably depends on your game module. SpringBoard core isn't that memory heavy (you're unlikely to hit the limit), but other games might go over.
Is this issue with SpringBoard Spring1944?

**Comment by sanguinariojoe** [comment]
> In any case, I don't think the problem is with texture_manager.lua - so the solution shouldn't be placed there either. Textures actually don't count to the 800MB Lua memory limits.

You are right, the problem is arised later. However, at such point, I monitored memory consumptions of 500MB (when large maps with complex textures are considered).

> Is this issue with SpringBoard Spring1944?

Yes, but I experienced similar problems with SpringBoard-Core

-----

I placed the silly patch in the texture_manager.py, and it worked to me. But probably you are right that better places can be found.

To provide more info to you (maybe it can help), the error is ever raised somewhere between these 2 log messages:

```
[f=0000294] [SpringBoard] Engine texture: splat_normals1
[f=0000298] [SpringBoard] Loading model...
```

But I don't actually think it is related with `Spring.SetHeightMapFunc`. I also tracked a bit more the memory, and I noticed it is significantly growing when the textures of a folder are loaded (e.g. when you are selecting the brush pattern).

**Comment by gajop** [comment]
> You are right, the problem is arised later. However, at such point, I monitored memory consumptions of 500MB (when large maps with complex textures are considered).
Still, it's not due to actual Lua textures, they don't count towards the 800MB limit.

> I also tracked a bit more the memory, and I noticed it is significantly growing when the textures of a folder are loaded (e.g. when you are selecting the brush pattern).
Hmm, so the brush pattern selection thing is a separate issue. This happens because we need to load images (unsynced) and send them to synced so they can be used to modify synced maps (height, grass, metal). Are you hitting memory limits here? It's hard to profile this because `/debug` doesn't allow me to click on patterns so I don't know real memory usage there.

The real issue is Chili, it's what consumes most of the memory. 
There's a very long discussion about this on Spring's Discord in the #sy channel. I suggest you join there and search "can we increase the 800MB Lua limit?", and start reading from there. (Unfortunately no easy to way to link it).
The conclusion is that Chili objects are heavy. The solution would be to reduce memory usage for lists/grids as those become very memory expensive when there are many objects.


PS: Regarding this PR: my recommendation would be to try moving it elsewhere. Try putting it somewhere in widget.lua for now.

**Comment by sanguinariojoe** [comment]
> Hmm, so the brush pattern selection thing is a separate issue. This happens because we need to load images (unsynced) and send them to synced so they can be used to modify synced maps (height, grass, metal). Are you hitting memory limits here? It's hard to profile this because /debug doesn't allow me to click on patterns so I don't know real memory usage there.

No! The system hangs a bit, but is ever surviving. I just was speculating with the possibility that textures are, in general, more dangerous than we though. Anyway, probably we can check how many textures (of the same resolution) a folder may contain before the system boils down.

> There's a very long discussion about this on Spring's Discord in the #sy channel. I suggest you join there and search "can we increase the 800MB Lua limit?", and start reading from there. (Unfortunately no easy to way to link it).

I'll try to do that! (I'm a bit stupid, so probably I'm asking you for more details :-p )

> PS: Regarding this PR: my recommendation would be to try moving it elsewhere. Try putting it somewhere in widget.lua for now.

I guess that's not an urgent PR, so maybe we can better let it hanged while we investigate a bit further. Are you OK with that?

**Comment by gajop** [comment]
Yes I don't mind it hanging for a bit, but I feel like there are 3 things that can be done:
1) Implement a simple hax-fix in widget.lua, that does the garbage collect thing you wrote. This is a temporary solution.
2) Make Chili objects lighter in general. This can be done by smartly deciding when to use tables and metatables for inheritance and instancing.
3) Rewrite grid view to be more memory efficient, and not create as many Chili objects but instead use a small object pool and only have it appear as if there are many objects.

I think we should do 1), close this PR and then try to do 2). 

3) is a worst case solution which I would like to avoid unless absolutely necessary

**Pull request closed without merging**
