### PR TITLE
Improved serialization memory issues

### PR DESCRIPTION
**Pull request by sanguinariojoe**
I'm back with this topic! I have been tracking memory while loading, and I found the main bottle neck is the messages serialization/stringfication (by large). e.g. in a 32x32 map, tracking the serialization process we can see something like:

```
[f=0000144] [SpringBoard] CommandManager:execute
[f=0000144] [SpringBoard] MessageManager:sendMessage...
[f=0000144] [SpringBoard] Memory: 322 MB
[f=0000144] [SpringBoard] Serializing...
[f=0000144] [SpringBoard] Serialized!
[f=0000105] [SpringBoard] Memory: 322 MB
[f=0000105] [SpringBoard] ShowTable...
[f=0000105] [SpringBoard] Memory: 322 MB
[f=0000105] [SpringBoard]   ShowTable...
[f=0000105] [SpringBoard]   Memory: 322 MB
[f=0000105] [SpringBoard]     ShowTable...
[f=0000105] [SpringBoard]     Memory: 322 MB
[f=0000105] [SpringBoard]       ShowTable...
[f=0000105] [SpringBoard]       Memory: 322 MB
[f=0000105] [SpringBoard]       DONE!
[f=0000105] [SpringBoard]       Memory: 442 MB
[f=0000105] [SpringBoard]     ShowTable...
[f=0000105] [SpringBoard]     Memory: 459 MB
[f=0000105] [SpringBoard]     DONE!
[f=0000105] [SpringBoard]     Memory: 466 MB
[f=0000105] [SpringBoard]   DONE!
[f=0000105] [SpringBoard]   Memory: 467 MB
[f=0000106] Error: [LuaRules::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=GameFrame trace=[Internal Lua error: Call failure] not enough memory
[f=0000106] Error: [LuaUI::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=GameFrame trace=[Internal Lua error: Call failure] not enough memory
[f=0000106] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={808792881,805306368}bytes
[f=0000106] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={808792881,805306368}bytes
[f=0000106] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={808792881,805306368}bytes
[f=0000106] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={808792881,805306368}bytes
[f=0000106] Fatal: [spring_lua_alloc_log_error][handle=LuaUI][OOM] synced=0 {alloced,maximum}={808792881,805306368}bytes
```

The last memory message (before crash) is printed prior to the execution of `return table.concat(strings)` (savetable.lua:207), which requires duplicating all the memory inside `strings`. The new string should be send back once again, and duplicated again, so I would say the required memory can be computed as (467-322)x3 + 322 = 757MB

I suggest a bit more sophisticated serialization process by means of https://github.com/fperrad/lua-MessagePack library. To illustrate the benefits, we can consider the same 32x32 map, which is giving back a memory log like the following:

```
[f=0000144] [SpringBoard] CommandManager:execute
[f=0000144] [SpringBoard] MessageManager:sendMessage...
[f=0000144] [SpringBoard] Memory: 322 MB
[f=0000144] [SpringBoard] Serializing...
[f=0000144] [SpringBoard] Serialized!
[f=0000144] [SpringBoard] Memory: 322 MB
[f=0000144] [SpringBoard] Stringfied!
[f=0000144] [SpringBoard] Memory: 331 MB
```

In my opinion a dramatic memory consumption improvement...

### CODE REVIEW

**Comment by gajop** [comment]
Interesting work, thanks!

Currently I'm pretty sure that most of the memory consumption happens due to Chili objects being highly memory intensive. I've ran some tests to confirm that previously, and you can easily prove it to yourself by removing the unit or feature defs editor for any larger game (e.g. comment out https://github.com/Spring-SpringBoard/SpringBoard-Core/blob/master/scen_edit/view/object/object_defs_view.lua#L241-L249). Optimizing serialization is a good thing and useful separately, so let's see if we can get this merged.

Regarding code, I'd recommend wrapping these calls with pcall as well: 
`msgTable = SB.messageManager.packer.unpack(msgParsed)`. I don't think we can guarantee parsing otherwise.

> The new string should be send back once again, and duplicated again, so I would say the required memory can be computed as (467-322)x3 + 322 = 757MB

I'm not sure about your math and how you got to 757 MBs. Can you elaborate a bit on where exactly you are measuring memory difference? I understand you're recording it in savetable.lua, but *when*? What command (CommandManager:execute) are you measuring?

The other thing I'm curious, how well was this tested? Previously I considered using json for message serialization, but it proved to be extremely slow whenever I wanted to load files. Have you tested this by loading large heightmaps? Modify the entire heightmap of a large map, save it, and then load the project.

**Comment by sanguinariojoe** [comment]
Yeah, Chili is memory hungry, no doubt... 280MB just to get SB working. However, I personally experienced the biggest memory issues when saving, loading and terraforming. And Fixing those is in fact my target right now.

> Regarding code, I'd recommend wrapping these calls with pcall as well:
msgTable = SB.messageManager.packer.unpack(msgParsed). I don't think we can guarantee parsing won't cause some errors otherwise.

OK! I'll do that... It is in fact causing errors. I'm discussing that later

> I'm not sure about your math and how you got to 757 MBs. Can you elaborate a bit on where exactly you are measuring memory difference? I understand you're recording it in savetable.lua, but when? What command (CommandManager:execute) are you measuring?

I started in `LoadProjectCommandWidget:execute()` (load_project_command_widget.lua:19). In such function a huge deadly command (heightmap + units & features) is set and "executed" in the following piece of code:

```
    local cmds = {LoadMapCommand(heightmapData), LoadModelCommand(modelData)}
    if not hasScenarioFile and Spring.GetGameRulesParam("sb_gameMode") == "play" then
        table.insert(cmds, StartCommand())
    end
    local cmd = CompoundCommand(cmds)
    cmd.blockUndo = true
    SB.commandManager:execute(cmd)
```

That redirects to `CommandManager:execute()` (command_manager.lua:107), which redirects to `MessageManager:sendMessage()` (message_manager.lua:32). The latter is then serializing the data with `MessageManager:__encodeToString()`, which was using `ShowTable()` (savetable.lua). If you need more details, just aks.

> The other thing I'm curious, how well was this tested? Previously I considered using json for message serialization, but it proved to be extremely slow whenever I wanted to load files. Have you tested this by loading large heightmaps? Modify the entire heightmap of a large map, save it, and then load the project.

You nailed the question... As far as I know, the new system is digesting the biggest possible heightmap, 32x32. So it is ever working? Nope... The unpack fails (or may fail) if the message has more than 16777215 bytes, because the counter is unable to correctly track the consumed bytes... :-/
That may happens when a lot of units & features are present in  the map.
I tried to use a BigNums implementation to minimize the problem... No success.
Hence, After merging that, I would split the mega-command into heightmap alone, and several loadmodel commands (with a maximum number of models per command), or something like... What do you think?

**Comment by gajop** [comment]
Sorry for the slow follow up.
Generally everything is good except this:
> Hence, After merging that, I would split the mega-command into heightmap alone, and several loadmodel commands (with a maximum number of models per command), or something like... What do you think?

I want to hide the message transportation intricacies from the logic. I don't think we should be changing how commands are scheduled, but instead we should focus on having the message library do that for us.

If the counter fails at some arbitrary number, then why not send the message in chunks? Spring puts a limit on how large the message can be, which is why I was sending it in chunks in my own implementation. You would need to concatenate it afterwards though. Is it possible to do that without incurring a memory issue for the concatenation operation?

**Comment by sanguinariojoe** [comment]
No problem, we are all busy :-)

> I want to hide the message transportation intricacies from the editor logic. I don't think we should be changing how commands are scheduled, but instead we should have the message library handle those details.
> 
> If the counter fails at some arbitrary number, then why not send the message in chunks? Spring puts a limit on how large the message can be, which is why I was sending it in chunks in my own implementation. You would need to concatenate it afterwards though. Is it possible to do that without incurring a memory issue for the concatenation operation?

In fact I would like to get something like that, but I'm afraid it is not possible at all... If you are able to fit and send a 32x32 heightmap then spring is probably returning the evil memory error later while calling Spring.SetHeightMapFunc (it survived a couple of times to me, but not usually). So if you wanna try to get a SpringBoard working "out of the box", then you should try to push spring guys to increment a bit the memory limit, or you should accept that some commands should be split

Like it is happening right now, you should in principle recompose the whole message/package after receiving that, in order to can interpret/unpack it. Hence it's not that easy. Anyway, I'm pretty confident I can do something to handle arbitrary big packages. However, please think about the possibility of commands split before

**Comment by gajop** [comment]
> 16777215  bytes

> If you are able to fit and send a 32x32 heightmap then spring is probably returning the evil memory error later while calling Spring.SetHeightMapFunc (it survived a couple of times to me, but not usually)

Aren't those two limits two different things? 16777215 bytes it around 16MB, which shouldn't be a problem. Hitting Spring limits (~800MB) is a different issue. If that happens from storing 32 x 32 maps heightmap in memory, then that's a different issue.

So I'm not sure what the issue is. I thought you were running into problems because you can't keep track of the number of elements (as 32bit floats can track up to 2^24=16777216 elements accurately). If that's the case, you can split it into multiple segments and merge those segments later.
If you are running into some issues with Spring memory limits, then that's a different thing. The first issue cannot be fixed by increasing Spring memory limits.
Which one is it?

**Comment by sanguinariojoe** [comment]
My point is, why would you try to send more than 16777215 bytes if you cannot handle them later because LUA memory errors?

Anyway, you are right... It's command dependant. So let's try to fix this issues (16777215 bytes limit), affording later other memory issues... I'm wrongly used to try to solve everything in one single shot :-p

I'll come with something! (Hopefully soon)

**Comment by gajop** [comment]
>  It's command dependant. So let's try to fix this issues (16777215 bytes limit), affording later other memory issues
> I'll come with something! (Hopefully soon)

Understood. Sounds good.
This can probably be merged as soon as that part is done. It's configurable so we can easily switch it off if it turns out to have some unexpected issues.

**Comment by sanguinariojoe** [comment]
Please, don't merge yet (just in case)

**Comment by gajop** [comment]
Don't worry. I'll wait for your OK.

**Comment by sanguinariojoe** [comment]
Well, I made several tests and I think the new pack/unpack system works fine.

As you may notice, in the last 2 commits I optimized the load project command

**Comment by gajop** [comment]
looks good to me now. can it be merged?

**Comment by sanguinariojoe** [comment]
Yes! (hopefully I'm not meshing up...).

**Comment by gajop** [comment]
Seems easy to try. Can always be disabled/reverted if it causes some issues.

**Comment by gajop** [comment]
Thanks again for the effort!

**Comment by sanguinariojoe** [comment]
Thanks!

**Pull request merged**
